stages:
  - stage: Stable
    condition: succeededOrFailed()
    jobs:
      - job: Windows_Stable
        displayName: "Windows - Stable"
        pool:
          name: Hosted VS2017
          demands: npm
        steps:
          - task: UsePythonVersion@0
            displayName: "Use Python (for pip)"
            inputs:
              versionSpec: "3.6"
              architecture: "x64"
          - task: NodeTool@0
            displayName: "Use Node 8.x"
            inputs:
              versionSpec: 8.x
          - task: Npm@1
            displayName: "Install dependencies"
            inputs:
              verbose: false
          - task: Npm@1
            displayName: "Lint"
            inputs:
              command: custom
              verbose: false
              customCommand: "run lint"
          - task: Npm@1
            displayName: "Compile sources"
            inputs:
              command: custom
              verbose: false
              customCommand: "run compile"
          - task: "Npm@1"
            displayName: "Run tests"
            inputs:
              command: custom
              customCommand: "run testWithoutCompile"
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: "jUnit"
              testResultsFiles: "out/test/results.xml"
            displayName: "Publish test results"
      - job: macOS_Stable
        displayName: "macOS - Stable"
        pool:
          name: Hosted macOS
          demands: npm
        steps:
          - task: UsePythonVersion@0
            displayName: "Use Python (for pip)"
            inputs:
              versionSpec: "3.6"
              architecture: "x64"
          - task: NodeTool@0
            displayName: "Use Node 8.x"
            inputs:
              versionSpec: 8.x
          - task: Npm@1
            displayName: "Install dependencies"
            inputs:
              verbose: false
          - task: Npm@1
            displayName: "Lint"
            inputs:
              command: custom
              verbose: false
              customCommand: "run lint"
          - task: Npm@1
            displayName: "Compile sources"
            inputs:
              command: custom
              verbose: false
              customCommand: "run compile"
          - task: "Npm@1"
            displayName: "Run tests"
            inputs:
              command: custom
              customCommand: "run testWithoutCompile"
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: "jUnit"
              testResultsFiles: "out/test/results.xml"
            displayName: "Publish test results"
      - job: Linux_Stable
        displayName: "Linux - Stable"
        pool:
          name: Hosted Ubuntu 1604
          demands: npm
        steps:
          - task: UsePythonVersion@0
            displayName: "Use Python (for pip)"
            inputs:
              versionSpec: "3.6"
              architecture: "x64"
          - task: NodeTool@0
            displayName: "Use Node 8.x"
            inputs:
              versionSpec: 8.x
          - task: Npm@1
            displayName: "Install dependencies"
            inputs:
              verbose: false
          - task: Npm@1
            displayName: "Lint"
            inputs:
              command: custom
              verbose: false
              customCommand: "run lint"
          - task: Npm@1
            displayName: "Compile sources"
            inputs:
              command: custom
              verbose: false
              customCommand: "run compile"
          - script: |
              set -e
              /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
              disown -ar
            displayName: "Start xvfb"
          - task: "Npm@1"
            displayName: "Run tests"
            inputs:
              command: custom
              customCommand: "run testWithoutCompile"
            env:
              DISPLAY: :10
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: "jUnit"
              testResultsFiles: "out/test/results.xml"
            displayName: "Publish test results"
  - stage: Insiders
    condition: succeededOrFailed()
    jobs:
      - job: Windows_Insiders
        displayName: "Windows - Insiders"
        pool:
          name: Hosted VS2017
          demands: npm
        steps:
          - task: UsePythonVersion@0
            displayName: "Use Python (for pip)"
            inputs:
              versionSpec: "3.6"
              architecture: "x64"
          - task: NodeTool@0
            displayName: "Use Node 8.x"
            inputs:
              versionSpec: 8.x
          - task: Npm@1
            displayName: "Install dependencies"
            inputs:
              verbose: false
          - task: Npm@1
            displayName: "Lint"
            inputs:
              command: custom
              verbose: false
              customCommand: "run lint"
          - task: Npm@1
            displayName: "Compile sources"
            inputs:
              command: custom
              verbose: false
              customCommand: "run compile"
          - task: "Npm@1"
            displayName: "Run tests"
            inputs:
              command: custom
              customCommand: "run testWithoutCompileInsiders"
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: "jUnit"
              testResultsFiles: "out/test/results.xml"
            displayName: "Publish test results"
      - job: macOS_Insiders
        displayName: "macOS - Insiders"
        pool:
          name: Hosted macOS
          demands: npm
        steps:
          - task: UsePythonVersion@0
            displayName: "Use Python (for pip)"
            inputs:
              versionSpec: "3.6"
              architecture: "x64"
          - task: NodeTool@0
            displayName: "Use Node 8.x"
            inputs:
              versionSpec: 8.x
          - task: Npm@1
            displayName: "Install dependencies"
            inputs:
              verbose: false
          - task: Npm@1
            displayName: "Lint"
            inputs:
              command: custom
              verbose: false
              customCommand: "run lint"
          - task: Npm@1
            displayName: "Compile sources"
            inputs:
              command: custom
              verbose: false
              customCommand: "run compile"
          - task: "Npm@1"
            displayName: "Run tests"
            inputs:
              command: custom
              customCommand: "run testWithoutCompileInsiders"
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: "jUnit"
              testResultsFiles: "out/test/results.xml"
            displayName: "Publish test results"
      - job: Linux_Insiders
        displayName: "Linux - Insiders"
        pool:
          name: Hosted Ubuntu 1604
          demands: npm
        steps:
          - task: UsePythonVersion@0
            displayName: "Use Python (for pip)"
            inputs:
              versionSpec: "3.6"
              architecture: "x64"
          - task: NodeTool@0
            displayName: "Use Node 8.x"
            inputs:
              versionSpec: 8.x
          - task: Npm@1
            displayName: "Install dependencies"
            inputs:
              verbose: false
          - task: Npm@1
            displayName: "Lint"
            inputs:
              command: custom
              verbose: false
              customCommand: "run lint"
          - task: Npm@1
            displayName: "Compile sources"
            inputs:
              command: custom
              verbose: false
              customCommand: "run compile"
          - script: |
              set -e
              /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
              disown -ar
            displayName: "Start xvfb"
          - task: "Npm@1"
            displayName: "Run tests"
            inputs:
              command: custom
              customCommand: "run testWithoutCompileinsiders"
            env:
              DISPLAY: :10
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: "jUnit"
              testResultsFiles: "out/test/results.xml"
            displayName: "Publish test results"
